name: ko_swipe_card
description: A FlutterSwipeCard package.
version: 1.0.0
homepage: https://github.com/CJR10032/ko_swipe_card.git

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

